language: cpp
compiler: gcc
os: linux
dist: bionic

cache:
  directories: 
  - build/

jobs:
  allow_failures:
  - os: osx
    stage: "Test"
  include:
    - stage: "Clear cache"
    # Bionic
      script: rm -rf build
    # MacOs
    - script: rm -rf build
      os: osx
      
    - stage: "Build"
    # Bionic
      script: ci/build.sh
      before_script: 
      - sudo apt-get update -qq
      - sudo apt-get install libboost-dev libboost-program-options-dev
    # MacOs
    - script: ci/build.sh
      os: osx
      before_script:
      - brew install libelf
      before_cache: touch build/osx_build_$TRAVIS_TEST_RESULT
      
    - stage: "Test"
    # Bionic
      script: ci/test.sh
    # MacOs
    - script: ci/test.sh
      os: osx
      before_cache: touch build/osx_test_$TRAVIS_TEST_RESULT
    
    - stage: "Deploy"
    # Bionic
      if: tag IS present
      script: skip
      deploy:
      - provider: releases
        api_key:
          secure: Tx8Cly4BWULJRyi5hgqvzz/IBhvqCKrGTulYzwdMLN34jBY6u4DvvAoFh1Zq4GXl9bm7Ire8Fjta7+PNorUYFgO6vnqL8GZ+sBR4FMNp/6XIt2xJqW/L4G6pdxV3BxdspAbVWLeMGH7FF8jNPmeWmTvRJbItgagG6cYUtEiiV9+e9E6aSiGQM2zkHSKmcRWHexf30iaR2pVSXzIWb2/hPlqQBj/bTXqEeTXkdiHH2/BtFjA7GmR45WbQUH48Nl94LDAFHW+TSJty0dw3wRxiF4O4bQIqlUmBSLrxcI344uQMu2M3u09N+PcJ1wgtacxRFbtK5FfrpatyjJPdjjb35klgCasGX33ktDLCcQW/g2qI8e2DdNQ9GfUCDmoIRxqQaoqRVMOkf0/KF2A+djlnTryYjwAVCmoRwmCX82wAG9WOsrhfN6HtuXIlCqj535Yqyey7G8OSB64qL+551RwQKUwrAM9Px3eH42epxKUgOIbQ1Arew0n2C3YnnJYE+xV15v3dyuitfQJSNOSaTk0HZ2kKocPiW0aPBJQLK/29bss3GVmL3MhsRlxnczs0wW3onz0p50FJ6ebrM90GcGOLH5tuyOjcXZM8dDcy6oPKgBhYJ9zKLQ5l++rlpkcIrjTyQnGGVfllCqmEcHXYYqBDYU9rNmbPANiJSRt41lNXi98=
        file_glob: true
        file: "build/patmos-simulator*.tar.gz"
        skip_cleanup: true
        on:
          tags: true
          repo: t-crest/patmos-simulator
    # MacOs  
    - os: osx
      if: tag IS present
      script: skip
      before_script:
      - test -f build/osx_build_0 # Ensure build succeeded
      deploy:
      - provider: releases
        api_key:
          secure: Tx8Cly4BWULJRyi5hgqvzz/IBhvqCKrGTulYzwdMLN34jBY6u4DvvAoFh1Zq4GXl9bm7Ire8Fjta7+PNorUYFgO6vnqL8GZ+sBR4FMNp/6XIt2xJqW/L4G6pdxV3BxdspAbVWLeMGH7FF8jNPmeWmTvRJbItgagG6cYUtEiiV9+e9E6aSiGQM2zkHSKmcRWHexf30iaR2pVSXzIWb2/hPlqQBj/bTXqEeTXkdiHH2/BtFjA7GmR45WbQUH48Nl94LDAFHW+TSJty0dw3wRxiF4O4bQIqlUmBSLrxcI344uQMu2M3u09N+PcJ1wgtacxRFbtK5FfrpatyjJPdjjb35klgCasGX33ktDLCcQW/g2qI8e2DdNQ9GfUCDmoIRxqQaoqRVMOkf0/KF2A+djlnTryYjwAVCmoRwmCX82wAG9WOsrhfN6HtuXIlCqj535Yqyey7G8OSB64qL+551RwQKUwrAM9Px3eH42epxKUgOIbQ1Arew0n2C3YnnJYE+xV15v3dyuitfQJSNOSaTk0HZ2kKocPiW0aPBJQLK/29bss3GVmL3MhsRlxnczs0wW3onz0p50FJ6ebrM90GcGOLH5tuyOjcXZM8dDcy6oPKgBhYJ9zKLQ5l++rlpkcIrjTyQnGGVfllCqmEcHXYYqBDYU9rNmbPANiJSRt41lNXi98=
        file_glob: true
        file: "build/patmos-simulator*.tar.gz"
        skip_cleanup: true
        on:
          tags: true
          repo: t-crest/patmos-simulator