language: cpp
compiler: gcc
os: linux
dist: bionic

cache:
  directories: 
  - build/
  
import:
- source: ci/deploy_config.yml
  if: DEPLOYMENT = deploy

jobs:
  allow_failures:
  - os: osx
  include:
    - stage: "Clear cache"
    # Bionic
      script: rm -rf build
    # MacOs
    - script: rm -rf build
      os: osx
      
    - stage: "Build"
    # Bionic
      script: ci/build.sh
      before_script: 
      - sudo apt-get update -qq
      - sudo apt-get install libboost-dev libboost-program-options-dev
    # MacOs
    - script: ci/build.sh
      os: osx
      before_script:
      - brew install libelf
      # We need GNU Tar instead of default BSD one for deployment
      - brew install gnu-tar
      - PATH="$(brew --prefix)/opt/gnu-tar/libexec/gnubin:$PATH"
      
    - stage: "Test"
    # Bionic
      script: ci/test.sh
    # MacOs
    - script: ci/test.sh
      os: osx
      after_success: touch build/osx_test_success
    
    - stage: "Deploy"
    # Bionic
      if: tag IS present
      script: skip
      env: DEPLOYMENT=deploy
    # MacOs  
    - os: osx
      if: tag IS present
      script: skip
      env: DEPLOYMENT=deploy
      # We need GNU Tar instead of default BSD one for deployment
      before_script:
      - test -f build/osx_test_success
      - brew install gnu-tar
      - PATH="$(brew --prefix)/opt/gnu-tar/libexec/gnubin:$PATH"